theme: readthedocs
site_name: SIMA Documentation
google_analytics: ['UA-35617728-3', 'auto']
site_dir: E:\Papyrus\Salesman Agenda\RC\es-ES
pages: 
- 'SIMA Salesman Agenda - Inicio': 'index.md'
- 'Salesman Agenda': 'Salesman Agenda.md'
- 'Nueva funcionalidad': 'Nueva funcionalidad.md'
- 'Crear acción': 'Crear accion.md'
- 'Seguimiento de ofertas': 'Seguimiento de ofertas.md'
- 'Versiones': 'Versiones.md'

