theme: readthedocs
site_name: SIMA Documentation
google_analytics: ['UA-35617728-3', 'auto']
site_dir: E:\Papyrus\EITV\RC\en-GB
pages: 
- 'Home': 'index.md'
- 'EITV': 'EITV.md'
- 'New feature': 'New feature.md'
- 'Version': 'Version.md'

