theme: readthedocs
site_name: SIMA Documentation
google_analytics: ['UA-35617728-3', 'auto']
site_dir: E:\Papyrus\Organizer\RC\en-GB
pages: 
- 'SIMA Service - Home': 'index.md'
- 'Organizer': 'Organizer.md'
- 'Mini-organizer': 'Mini-organizer.md'
- 'Panel of the mechanic': 'Panel of the mechanic.md'
- 'Configurations': 'Configurations.md'
- 'Versions': 'Versions.md'

