theme: readthedocs
site_name: SIMA Documentation
google_analytics: ['UA-35617728-3', 'auto']
site_dir: E:\Papyrus\Business Intelligence\RC\es-ES
pages: 
- 'Inicio': 'index.md'
- 'Business Intelligence': 'Business Intelligence.md'
- 'Conceptos de trabajo': 'Conceptos de trabajo.md'
- 'Sobre el versionado': 'Sobre el versionado.md'
- 'Versiones': 'Versiones.md'

