theme: readthedocs
site_name: SIMA Documentation
google_analytics: ['UA-35617728-3', 'auto']
site_dir: E:\Papyrus\Business Intelligence\RC\en-GB
pages: 
- 'Home': 'index.md'
- 'Business Intelligence': 'Business Intelligence.md'
- 'Core concepts': 'Core concepts.md'
- 'About versioning': 'About versioning.md'
- 'Versions': 'Versions.md'

