theme: readthedocs
site_name: SIMA Documentation
google_analytics: ['UA-35617728-3', 'auto']
site_dir: E:\Papyrus\Ordering\RC\es-ES
pages: 
- 'SIMA Sales - Inicio': 'index.md'
- 'Ordering': 'Ordering.md'
- 'Nuevo pedido': 'Nuevo pedido.md'
- 'Buscar pedidos': 'Buscar pedidos.md'
- 'Cancelaciones': 'Cancelaciones.md'
- 'Envíos de pedidos': 'Envios de pedidos.md'
- 'Llegadas de pedidos': 'Llegadas de pedidos.md'
- 'Histórico': 'Historico.md'
- 'Cesiones': 'Cesiones.md'
- 'Clientes': 'Clientes.md'
- 'Configuración': 'Configuracion.md'
- 'Subscribirme': 'Subscribirme.md'
- 'Versiones': 'Versiones.md'

